# Generated by Django 4.2.5 on 2023-11-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keterangan',
            fields=[
                ('kode_keterengan', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('keterangan', models.TextField()),
                ('cf', models.CharField(max_length=50)),
            ],
        ),
    ]
