# Generated by Django 4.2.5 on 2023-11-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0002_keterangan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keterangan',
            old_name='kode_keterengan',
            new_name='kode_keterangan',
        ),
    ]
