# Generated by Django 4.2.5 on 2023-11-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0006_alter_keterangan_kode_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keterangan',
            name='kode_keterangan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
