# Generated by Django 4.2.5 on 2023-12-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0009_alter_keterangan_kode_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
                ('kode_gejala', models.CharField(max_length=3)),
                ('p1', models.CharField(max_length=50)),
                ('p2', models.CharField(max_length=50)),
                ('p3', models.CharField(max_length=50)),
            ],
        ),
    ]
