# Generated by Django 4.2.5 on 2023-12-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0010_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserPasien',
        ),
    ]
