# Generated by Django 4.2.5 on 2023-12-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0011_rename_user_userpasien'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasien',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
