# Generated by Django 4.2.6 on 2023-12-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0012_userpasien_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasien',
            name='kode_gejala',
        ),
        migrations.RemoveField(
            model_name='userpasien',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='userpasien',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='userpasien',
            name='p3',
        ),
        migrations.AddField(
            model_name='userpasien',
            name='gejala',
            field=models.ManyToManyField(to='depresi_app.gejala'),
        ),
        migrations.AlterField(
            model_name='keterangan',
            name='cf',
            field=models.FloatField(),
        ),
    ]
