# Generated by Django 4.2.6 on 2023-12-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0013_remove_userpasien_kode_gejala_remove_userpasien_p1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasien',
            name='gejala',
        ),
        migrations.CreateModel(
            name='GejalaBobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot', models.FloatField()),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depresi_app.gejala')),
                ('user_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depresi_app.userpasien')),
            ],
        ),
        migrations.AddField(
            model_name='userpasien',
            name='gejala_bobot',
            field=models.ManyToManyField(through='depresi_app.GejalaBobot', to='depresi_app.gejala'),
        ),
    ]
