# Generated by Django 4.2.6 on 2023-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0014_remove_userpasien_gejala_gejalabobot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasien',
            name='gejala_bobot',
        ),
        migrations.AddField(
            model_name='userpasien',
            name='kode_gejala',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userpasien',
            name='p1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userpasien',
            name='p2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userpasien',
            name='p3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='keterangan',
            name='cf',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='GejalaBobot',
        ),
    ]
