# Generated by Django 4.2.6 on 2023-12-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depresi_app', '0015_remove_userpasien_gejala_bobot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasien',
            name='cf',
            field=models.CharField(default='', max_length=100),
        ),
    ]
